import "./globals.css";

import { Oxanium } from "next/font/google";

import { cn } from "@/lib/utils";

const oxanium = Oxanium({
    variable: "--font-oxanium",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={cn(oxanium.variable, "font-oxanium", "h-full", "antialiased")}>
            <body className="min-h-full flex flex-col">
                <main
                    id="main"
                    className="max-w-7xl mx-auto p-20 flex flex-col flex-1 items-center justify-center"
                >
                    {children}
                </main>
            </body>
        </html>
    );
}

// inspiration: "React for Two Computers | Dan Abramov" -- https://youtu.be/ozI4V_29fj4
